secrets: secrets.yml
schedules:
  - tasks: Series
    interval:
      minutes: 15

templates:
  tv:

    thetvdb_lookup: yes

    deluge:
      main_file_only: yes
      magnetization_timeout: 60
      path: /media/pi/DeepStorage/Incomplete/
      label: TVShows

    configure_series:
      settings:
        quality: webdl|hdtv|webrip h264 720p
        propers: no
        set:
            content_filename: "{{ series_name }} - {{ series_id }} - {{ tvdb_ep_name|default('Unknown') }}  - {{ quality|upper }}"
            movedone: /media/pi/DeepStorage/TVShows/{{series_name}}/Season {{tvdb_season}}/
            removeatratio: 2.0
      ##############################Grab Series from trakt
      from:
        trakt_list:
          account: '{{ secrets.trakt.account }}'
          list: Following
          type: shows
          strip_dates: yes

    #################################Reject all series that exist
    exists_series:
      allow_different_qualities: yes 
      path: '/media/pi/DeepStorage/TVShows/{{series_name}}'
        #dont duplicate if we have it already

    regexp:
      reject:
        - (s|d)ub(s|bed)?\b: {from: title}
        - \b(duo|tri|quadri|tetra|penta)logy\b: {from: title}
        - \b3-?D\b: {from: title}
        - \btrailer\b: {from: title}
        - \bR5\b: {from: title}
        - \bWEBSCR\b: {from: title}
        - \bscreener\b: {from: title}
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - '{C_P}': {from: title}
        - TrTd TeaM: {from: title}
        - \[TNTVillage\]: {from: title}
        - \bASAP\b: {from: title}  

    torrent_alive:
      min_seeds: 10
      reject_for: 1 hours

    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mpg'
        - '*.mp4'
        - '*.r0*'
        - '*.part0*'

      reject:
        - 'password.txt'
        - '*.wmv' 

    content_size:
      min: 400
      max: 3000
      strict: no

    #pushbullet:
      #apikey: PUSHBULLET_API_KEY
      #title: "[F](/F) {{series_name}} {{series_id}}"
      #body: "{{title}}\n\nSize: {{content_size}}MB"


    ##############################Search for torrents
    inputs:
      - rss:
          url: https://zooqle.com/search?q={{search_term}}&fmt=rss 
          all_entries: no
      - rss:
          url: '{{ secrets.rss.site2 }}'
          all_entries: no


tasks:
  Series:
    template: tv
    priority: 1
