secrets: secrets.yml

schedules:
  - tasks: sync-trakt
    interval:
      hours: 24
  - tasks: grab_series
    interval:
      hours: 1
      
#irc:
#  is: 
#    tracker_file: 'is.tracker' #immortal seed
#    nickname: 'jsqribe' #make sure to check naming conventions before joining
#    nickserv_password: '{{ secrets.irc.isnickserv }}'
#    port: 7011
#    rsskey: '{{ secrets.rss.is}}'
#    task: get_entry
#   channels: ["#immortal"]      
            
      
templates:
  tv:
    thetvdb_lookup: yes

    deluge:
      main_file_only: yes
      magnetization_timeout: 60
      path: /media/pi/DeepStorage/Incomplete/
      label: TVShows
    
    configure_series:
      settings:
        #quality: webdl|hdtv|webrip h264 20p 1080p
        upgrade: yes #just take any qualities and keep getting better ones
        propers: no
        identified_by: ep
        set:
          content_filename: "{{ series_name }} - {{ series_id }} - {{ tvdb_ep_name|default('Unknown') }}  - {{ quality|upper }}"
          movedone: /media/pi/DeepStorage/TVShows/{{series_name}}/Season {{tvdb_season}}/
          removeatratio: 1.0
      from:
        trakt_list:
          account: '{{ secrets.trakt.account }}'
          list: Following
          type: shows
          strip_dates: yes


    discover:
      what: 
        - next_series_episodes: yes
      from:
        - search_rss: https://zooqle.com/search?q={{search_term}}&fmt=rss 
        - search_rss: '{{ secrets.rss.site2 }}' #showRSS
        #- search_rss: '{{ secrets.rss.site3 }}' #HoT
        #- search_rss: '{{ secrets.rss.site4 }}' #HD4F
        #- search_rss: alpha reign :D

    #################################Reject all series that exist
    exists_series: 
      path: '/media/pi/DeepStorage/TVShows'
      #dont duplicate if we have it already
      allow_different_qualities: better #unless we can grab a better version

    regexp:
      reject:
        - (s|d)ub(s|bed)?\b: {from: title}
        - \b(duo|tri|quadri|tetra|penta)logy\b: {from: title}
        - \b3-?D\b: {from: title}
        - \btrailer\b: {from: title}
        - \bR5\b: {from: title}
        - \bWEBSCR\b: {from: title}
        - \bscreener\b: {from: title}
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - '{C_P}': {from: title}
        - TrTd TeaM: {from: title}
        - \[TNTVillage\]: {from: title}
        - \bASAP\b: {from: title}  

    torrent_alive:
      min_seeds: 5
      reject_for: 1 hours

    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mpg'
        - '*.mp4'
        - '*.r0*'
        - '*.part0*'

      reject:
        - 'password.txt'
        - '*.wmv' 

    content_size:
      min: 200
      max: 4000
      strict: no

    pushbullet:
      api_key: '{{ secrets.pushbullet.key }}'
      title: "Downloading {{series_name}} {{series_id}}"
      message: "{{title}}\n\nSize: {{content_size}}MB"

tasks:
  grab_series:
    template: tv
    priority: 2

  sync-trakt:
    priority: 1
    next_trakt_episodes:
      account: '{{ secrets.trakt.account }}'
      list: Following
      strip_dates: yes
    accept_all: yes
    set_series_begin: yes

