web_server: no

presets:
  global:
    free_space:
      path: /media/pi/DeepStorage
      space: 50000
    verify_ssl_certificates: no
    torrent_alive:
      min_seeds: 10
      reject_for: 3 hours
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mpg'
        - '*.mp4'
        - '*.r0*'
        - '*.part0*'
      reject:
        - 'password.txt'
        - '*.wmv'
    thetvdb_lookup: yes
    #magnets: no
    imdb_lookup: yes
    regexp:
      reject:
        - (s|d)ub(s|bed)?\b: {from: title}
        - \b(duo|tri|quadri|tetra|penta)logy\b: {from: title}
        - \b3-?D\b: {from: title}
        - \btrailer\b: {from: title}
        - \bR5\b: {from: title}
        - \bWEBSCR\b: {from: title}
        - \bscreener\b: {from: title}
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - '{C_P}': {from: title}
        - TrTd TeaM: {from: title}
        - \[TNTVillage\]: {from: title}
        - \bASAP\b: {from: title}
    deluge:
      main_file_only: yes

tasks:
  TV_Series:
    discover:
      what:
        - next_series_episodes: yes
      from:
        - search_rss: https://zooqle.com/search?q={{search_term}}&fmt=rss 

    series:
      thetvdb_lookup: yes
      settings:
        default:
          begin: S01E01
          set:
            content_filename: "{{ series_name }} - {{ series_id }} - {{ tvdb_ep_name|default('Unknown') }}  - {{ quality|upper }}"
            movedone: /media/pi/DeepStorage/TVShows/{{series_name}}/Season {{tvdb_season}}/
            removeatratio: 1.0

      default:
        - Vikings
        #lit show


    deluge:
      magnetization_timeout: 60
      path: /media/pi/DeepStorage/Incomplete/
      label: tv


