web_server: no

tasks:
  TV_Series:
    discover:
      what:
        - next_series_episodes: yes
      from:
        - search_rss: https://zooqle.com/search?q={{search_term}}&fmt=rss 
    series:
      settings:
        default:
          begin: S01E01
          thetvdb_lookup: yes
          set:
            content_filename: "{{ series_name }} - {{ series_id }} - {{ tvdb_ep_name|default('Unknown') }}  - {{ quality|upper }}"
          movedone: /media/pi/DeepStorage/TVShows/{{series_name}}/Season {{tvdb_season}}/
      default:
        - Vikings
        #lit show
    deluge:
      magnetization_timeout: 60
      path: /media/pi/DeepStorage/Incomplete/
      label: tv

